/* L�gico_1: */

CREATE TABLE Pizza_Sabor (
    ID_Pizza INTEGER PRIMARY KEY,
    Tamanho_M FLOAT,
    Tamanho_G FLOAT,
    NOME_PIZZA VARCHAR
);

CREATE TABLE Cliente (
    ID_CLIENTE INTEGER PRIMARY KEY,
    ENDERECO VARCHAR,
    TELEFONE INTEGER,
    CELULAR INTEGER,
    NOME_CLIENTE VARCHAR,
    fk_Pizza_Sabor_ID_Pizza INTEGER,
    fk_BEBIDA_ID_BEBIDA INTEGER
);

CREATE TABLE PAGAMENTO (
    PIX VARCHAR,
    DINHEIRO VARCHAR,
    CARTAO VARCHAR,
    ID_PAGAMENTO INTEGER PRIMARY KEY,
    FK_Pizza_Sabor_ID_Pizza INTEGER,
    FK_BEBIDA_ID_BEBIDA INTEGER
);

CREATE TABLE BEBIDA (
    ID_BEBIDA INTEGER PRIMARY KEY,
    TAMANHO_P FLOAT,
    TAMANHO_M FLOAT,
    TAMANHO_G FLOAT,
    NOME_BEBIDA VARCHAR
);

CREATE TABLE ATENDENTE (
    ID_ATENDENTE INTEGER PRIMARY KEY,
    NOME VARCHAR,
    IDADE INTEGER,
    SEXO VARCHAR
);

CREATE TABLE POSSUI (
    FK_ATENDENTE_ID_ATENDENTE INTEGER,
    FK_Cliente_ID_CLIENTE INTEGER
);
 
ALTER TABLE Cliente ADD CONSTRAINT FK_Cliente
    FOREIGN KEY (fk_Pizza_Sabor_ID_Pizza)
    REFERENCES Pizza_Sabor (ID_Pizza)
    ON DELETE RESTRICT;
 
ALTER TABLE Cliente ADD CONSTRAINT FK_Cliente
    FOREIGN KEY (fk_BEBIDA_ID_BEBIDA)
    REFERENCES BEBIDA (ID_BEBIDA)
    ON DELETE RESTRICT;
 
ALTER TABLE PAGAMENTO ADD CONSTRAINT FK_PAGAMENTO
    FOREIGN KEY (FK_Pizza_Sabor_ID_Pizza)
    REFERENCES Pizza_Sabor (ID_Pizza)
    ON DELETE RESTRICT;
 
ALTER TABLE PAGAMENTO ADD CONSTRAINT FK_PAGAMENTO
    FOREIGN KEY (FK_BEBIDA_ID_BEBIDA)
    REFERENCES BEBIDA (ID_BEBIDA)
    ON DELETE RESTRICT;


ALTER TABLE Cliente ADD CONSTRAINT FK_ATENDENTE
    FOREIGN KEY (FK_ATENDENTE_ID_ATENDENTE)
    REFERENCES ATENDENTE (ID_ATENDENTE)
    ON DELETE RESTRICT;
 
 
